# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teasite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
