# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teasite', '0002_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sugar',
            field=models.BooleanField(default=True),
        ),
    ]
